# =====================Numpy练习100题=========================

# 必做题

## 1. 导入numpy库并简写为 np
### (提示: import ... as ...)

In [5]:
import numpy as np

## 2. 打印numpy的版本和配置说明
### (提示: np.version, np.show_config)

In [6]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not

## 3. 创建一个长度为10的空向量
### (提示: np.zeros)

In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4. 如何找到任何一个数组的内存大小？
### (提示: size, itemsize)

In [4]:
z=np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))


800 bytes


## 5. 如何从命令行得到numpy中add函数的说明文档?
### (提示: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## 6. 创建一个长度为10并且除了第五个值为1的空向量
### (提示: array[4])

In [6]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个值域范围从10到49的向量
### (提示: np.arange)

In [7]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. 反转一个向量(第一个元素变为最后一个)
### (提示: array[::-1])

In [8]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 9. 创建一个 3x3 并且值从0到8的矩阵
### (提示: reshape)

In [9]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
### (提示: np.nonzero)

In [10]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


## 11. 创建一个 3x3 的单位矩阵
### (提示: np.eye)

In [11]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12. 创建一个 3x3x3的随机数组 
### (提示: np.random.random)

In [12]:
z=np.random.random((3,3,3))
print(z)

[[[0.14087662 0.31884417 0.24726011]
  [0.54824905 0.3719393  0.74810952]
  [0.36427564 0.10153414 0.33722296]]

 [[0.49200976 0.8496636  0.78458732]
  [0.58698932 0.9741315  0.00108212]
  [0.46607805 0.12302572 0.40055206]]

 [[0.2365919  0.86116796 0.12446283]
  [0.9337639  0.28805608 0.17558394]
  [0.75377201 0.14169408 0.08147986]]]


## 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 
### (提示: min,max)

In [13]:
z=np.random.random((10,10))
zmax=z.max()
zmin=z.min()
print(zmax,zmin)

0.9918905565648135 0.0017470666076248031


## 14. 创建一个长度为30的随机向量并找到它的平均值 
### (提示: mean)

In [14]:
z=np.random.random(30)
m=z.mean()
print(m)

0.459173304352828


## 15. 创建一个二维数组，其中边界值为1，其余值为0 
### (提示: array[1:-1, 1:-1])

In [15]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 16. 对于一个存在的数组，如何添加一个用0填充的边界？
### (提示: np.pad)

In [16]:
z=np.zeros((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=1)
print(z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## 17. 以下表达式运行的结果分别是什么?
### (提示: NaN = not a number, inf = infinity)

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [18]:
print(0 * np.nan)
print(np.nan ==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18.创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
### (提示: np.diag)

In [19]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19.创建一个8x8 的矩阵，并且设置成棋盘样式
### (提示: array[::2])

In [20]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20.考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么 
### (提示: np.unravel_index)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## 21.用tile函数去创建一个 8x8的棋盘样式矩阵
### (提示: np.tile)

In [22]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22.对一个5x5的随机矩阵做归一化
### (提示: (x - min) / (max - min))

In [23]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.42818886 -1.48945869  0.85751348 -0.90879402  0.0903522 ]
 [-1.24668397 -0.50929906 -1.66311809 -1.07058534  1.04628054]
 [ 1.09538836 -1.47851176  0.60921436  0.52271167  0.42416946]
 [ 0.4596627  -1.5238286   1.30364427 -0.49788202 -0.10090549]
 [ 1.39162829  1.39813209  0.89759719 -0.07593949  0.8969008 ]]


## 23.创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
### (提示: np.dtype)

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

## 24.一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
### (提示: np.dot | @)

In [25]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 25.给定一个一维数组，对其在3到8之间的所有元素取反
### (提示: >, <=)

In [26]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 26.下面脚本运行后的结果是什么?
### (提示: np.sum)

In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


## 27.考虑一个整数向量Z,下列表达合法的是哪个?

In [35]:
Z**Z
2 << Z >> 2
Z <- Z 
1j*Z 
Z/1/1 
Z<Z>Z 

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [38]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

## 28.下列表达式的结果分别是什么?

In [3]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\YuDan\AppData\Local\Temp\ipykernel_13544\548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\YuDan\AppData\Local\Temp\ipykernel_13544\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [2]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\YuDan\AppData\Local\Temp\ipykernel_13544\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\YuDan\AppData\Local\Temp\ipykernel_13544\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


## 29.如何从零位对浮点数组做舍入 ?
### (提示: np.uniform, np.copysign, np.ceil, np.abs)

In [10]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ -2.   3.  -6.  -2.  -9. -10.   6.  -3.  -1.   1.]


## 30.如何找到两个数组中的共同元素?
### (提示: np.intersect1d)

In [11]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 9]


## 31.如何忽略所有的 numpy 警告(尽管不建议这么做)?
### (提示: np.seterr, np.errstate)

In [12]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

## 32.下面的表达式是正确的吗? 
### (提示: imaginary number)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

In [15]:
False

False

## 33.如何得到昨天，今天，明天的日期?
### (提示: np.datetime64, np.timedelta64)

In [14]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

## 34.如何得到所有与2016年7月对应的日期？
### (提示: np.arange(dtype=datetime64['D']))

In [16]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 35.如何直接在位计算(A+B)*(-A/2)(不建立副本)? 
### (提示: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [17]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 36.用五种不同的方法去提取一个随机数组的整数部分
### (提示: %, np.floor, np.ceil, astype, np.trunc)

In [18]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[5. 7. 2. 4. 9. 7. 1. 8. 3. 7.]
[5. 7. 2. 4. 9. 7. 1. 8. 3. 7.]
[5. 7. 2. 4. 9. 7. 1. 8. 3. 7.]
[5 7 2 4 9 7 1 8 3 7]
[5. 7. 2. 4. 9. 7. 1. 8. 3. 7.]


## 37.创建一个5x5的矩阵，其中每行的数值范围从0到4
### (提示: np.arange)

In [19]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 38.通过考虑一个可生成10个整数的函数，来构建一个数组
### (提示: np.fromiter)

In [20]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 39.创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
### (提示: np.linspace)

In [21]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 40.创建一个长度为10的随机向量，并将其排序
### (提示: sort)

In [22]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06094483 0.08218045 0.38724084 0.40667276 0.41373675 0.45198033
 0.48328895 0.75272974 0.79110595 0.97393062]


## 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
### (提示: np.add.reduce)

In [23]:
Z = np.arange(10)
np.add.reduce(Z)

45

## 42.对于两个随机数组A和B，检查它们是否相等
### (提示: np.allclose, np.array_equal)

In [24]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


## 43.创建一个只读数组(read-only)
### (提示:flags.writeable)

In [26]:
Z = np.zeros(10)
Z.flags.writeable = False

## 44.将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
### (提示: np.sqrt, np.arctan2)

In [27]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.97368154 0.95035729 0.71766075 1.01612723 1.0210433  1.06034531
 0.8801614  0.65344402 0.66707559 0.53787757]
[0.65314184 0.25212506 1.05524039 0.32448681 1.07035673 0.90759234
 0.02368124 0.22262172 0.60288219 0.79839316]


## 45.创建一个长度为10的向量，并将向量中最大值替换为1 
### (提示: argmax)

In [28]:
Z = np.random.random(10)
Z[Z.argmax()] = 1
print(Z)

[0.95325767 0.85588611 0.16695822 0.48112059 0.49555408 1.
 0.3143389  0.26920016 0.96039254 0.56760128]


## 46.创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
### (提示: np.meshgrid)

In [29]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 47.给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
### (提示: np.subtract.outer)

In [30]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


## 48.打印每个numpy标量类型的最小值和最大值
### (提示: np.iinfo, np.finfo, eps)

In [31]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49.如何打印一个数组中的所有数值
### (提示: np.set_printoptions)

In [32]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 50.给定标量时，如何找到数组中最接近标量的值
### (提示: argmin)

In [33]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

63


# 进阶题（感兴趣的同学可以尝试一下）

## 51.创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
### (提示:dtype)

## 52.对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
### (提示:np.atleast_2d, T, np.sqrt)

## 53.如何将32位的浮点数(float)转换为对应的整数(integer)?
### (提示:astype(copy=False))

## 54.如何读取以下文件?
### (提示:np.genfromtxt)

In [ ]:
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

## 55.对于numpy数组，enumerate的等价操作是什么？
### (提示:np.ndenumerate, np.ndindex)

## 56.生成一个通用的二维Gaussian-like数组
### (提示:np.meshgrid, np.exp)

## 57.对一个二维数组，如何在其内部随机放置p个元素?
### (提示:np.put, np.random.choice)

## 58.减去一个矩阵中的每一行的平均值
### (提示:mean(axis=,keepdims=))

## 59.如何通过第n列对一个数组进行排序
### (提示:argsort)

## 60.如何检查一个二维数组是否有空列
### (提示:any, ~)

## 61.从数组中的给定值中找出最近的值
### (提示:np.abs, argmin, flat)

## 62.如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
### (提示:np.nditer)

## 63.创建一个具有name属性的数组类
### (提示:class方法)

## 64.考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? 
### (提示:np.bincount | np.add.at)

## 65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)
### (提示:np.bincount)

## 66.考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
### (提示:np.unique)

## 67.考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？
### (提示:sum(axis=(-2,-1)))

## 68.考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
### (提示:np.bincount)

## 69.如何获得点积 dot prodcut的对角线?
### (提示:np.diag)

## 70.考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？
### (提示:array[::4])

## 71.考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
### (提示:array[:, :, None])

## 72.如何对一个数组中任意两行做交换?
### (提示:array[[]] = array[[]])

## 73.考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
### (提示:repeat, np.roll, np.sort, view, np.unique)

## 74.给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C
### (提示:np.repeat)

## 75.如何通过滑动窗口计算一个数组的平均数?
### (提示:np.cumsum)

## 76.Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
### (提示:from numpy.lib import stride_tricks)

## 77.如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？
### (提示:np.logical_not, np.negative)

## 78.考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

## 79.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary

## 80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary
### (提示:minimum, maximum)

## 81.考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], …,[11,12,13,14]]?
### (提示:stride_tricks.as_strided)

## 82.计算一个矩阵的秩
### (提示:np.linalg.svd)

## 83.如何找到一个数组中出现频率最高的值？
### (提示:np.bincount, argmax)

## 84.从一个10x10的矩阵中提取出连续的3x3区块？
### (提示:stride_tricks.as_strided)

## 85.创建一个满足 Z[i,j] == Z[j,i]的子类
### (提示:class 方法)

## 86.考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？
### (提示:np.tensordot)

## 87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? 
### (提示:class 方法)

## 88.创建一个满足 Z[i,j] == Z[j,i]的子类
### (提示:np.add.reduceat)

## 89.如何找到一个数组的第n个最大值?
### (提示: np.argsort | np.argpartition)

## 90.给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
### (提示:np.indices)

## 91.如何从一个正常数组创建记录数组(record array)?
### (提示:np.core.records.fromarrays)

## 92.考虑一个大向量Z, 用三种不同的方法计算它的立方
### (提示:np.power, *, np.einsum)

## 93.考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？
### (提示:np.where)

## 94.考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])

## 95.将一个整数向量转换为matrix binary的表现形式
### (提示:np.unpackbits)

## 96.给定一个二维数组，如何提取出唯一的(unique)行?
### (提示:np.ascontiguousarray)

## 97.考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
### (提示:np.einsum)

## 98.考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)
### (提示:np.cumsum, np.interp)

## 99.Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
### (提示:np.logical_and.reduce, np.mod)

## 100.对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值
### (提示:np.percentile)