# 1.幂方法
### 代码：

In [19]:
import numpy as np
err=10**(-5)
k=200
x1=np.array([1,1,1])
x2=np.array([1,1,1,1])
def power(A,x0,tol,maxit):
    lamda0=max(x0,key=abs)
    u=x0/lamda0
    while maxit>0:
        v=A.dot(u)
        lamda1=max(v,key=abs)
        u=v/lamda1
        if abs(lamda1-lamda0)<tol:
            break
        lamda0=lamda1
    return v,lamda0
A1=np.array([[1,3,3],[2,1,3],[3,3,6]])
A2=np.array([[-4,14,0],[-5,13,0],[-1,0,2]])
A3=np.array([[8,4,3,5],[7,2,4,1],[6,2,2,2],[1,0,4,3]])
print(power(A1,x1,err,k))
print(power(A2,x1,err,k))
print(power(A3,x2,err,k))

(array([5.06024871, 4.60700698, 9.16455761]), 9.164555167233821)
(array([ 6.00000654,  4.28572036, -1.49999673]), 6.0000130790190696)
(array([14.62709182, 11.47079993,  9.48318718,  4.52046379]), 14.627096732355023)


# 2.QR方法
### 代码：

In [21]:
import numpy as np
A=np.array([[5,2,2,1],[2,-3,1,1],[2,1,3,1],[1,1,1,2]])
tol=10**(-4)
err=1
while err>tol:
    q,r=np.linalg.qr(A)
    A1=r.dot(q)
    err=np.linalg.norm(np.diag(A1-A))
    A=A1
print(np.diag(A1))

[ 7.21833669 -3.60267036  1.99994695  1.38438673]


# 3.条件数
### 代码：

In [2]:
import numpy as np
from numpy.linalg import inv
def power(A,x,tol,maxit):
    n=x.shape
    eigval_=0
    eigvec=np.zeros(n)
    for it in range(maxit):
        eigval=max(x.min(),x.max(),key=abs)
        if abs(eigval-eigval_)<tol:
            break
        eigvec=x/eigval
        x=np.matmul(A,eigvec)
        eigval_=eigval
    if it==maxit-1:
        eigvec=np.zeros(n) 
        return eigvec,eigval
    eigvec=x/eigval
    return eigval
def invpower(A,x,tol,maxit):
    B=inv(A)
    n=x.shape
    eigval_=0
    eigvec=np.zeros(n)
    for it in range(maxit):
        eigval=max(x.min(),x.max(),key=abs)
        if abs(eigval-eigval_)<tol:
            break
        eigvec=x/eigval
        x=np.matmul(B,eigvec)
        eigval_=eigval
    if it==maxit-1:
        eigvec=np.zeros(n) 
        return eigvec,1/eigval
    eigvec=x/eigval
    return 1/eigval
tol=1e-5
maxit=200
cond=np.zeros(10)
j=0
for n in np.arange(100,1100,100):
    A=np.diag([2]*n)
    for i in range(n-1):
        A[i][i+1]=-1
        A[i+1][i]=-1
    x=np.ones(n)
    lambda1=power(A,x,tol,maxit)
    lambda2=invpower(A,x,tol,maxit)
    cond[j]=lambda1/lambda2
    j=j+1
print("n取100，200，……，1000时，矩阵条件数为：")
print(cond)

n取100，200，……，1000时，矩阵条件数为：
[  1033.66073249   4093.56047503   9179.88389375  16292.63098462
  25431.80174915  36597.39618659  49789.41429691  65007.8560801
  82252.72153617 101524.01066511]
