# 1. 正交矩阵判断
### 代码：

In [8]:
import numpy as np

a = np.asarray([[0,-1,0],
       [1,0,0],
       [0,0,1]])
b = a.transpose()
c=np.matmul(a,b)
print(np.allclose(np.eye(3),c))

True


# 2. 用 Givens 变换化上海森伯格矩阵为上三角阵
### 代码：

In [12]:
import numpy as np
import math

arr=np.array([[15,4,7,0,6],[12,3,0,24,9],[0,24,81,39,40],[0,0,32,21,33],[0,0,0,15,17]])
n=5

for i in range(n-1):
    G=np.eye(n)
    x1=arr[i][i]
    x2=arr[i+1][i]
    c=x1/(math.sqrt(x1**2+x2**2))
    s=x2/(math.sqrt(x1**2+x2**2))
    G[i][i]=c
    G[i+1][i+1]=c
    G[i][i+1]=s
    G[i+1][i]=-s
    arr=np.dot(G,arr)
np.set_printoptions(suppress=True)
print(arr)

[[19.20937271  4.99756038  5.46608167 14.99268114 10.30746828]
 [ 0.         24.00050812 81.0267398  38.87722568 39.97781213]
 [ 0.         -0.         32.2302558  18.58359224 32.34187038]
 [-0.          0.          0.         26.10423214 15.8674983 ]
 [ 0.         -0.          0.         -0.          9.63102035]]


# 3. 正交三角分解
### 代码：

In [13]:
def Schmidt(A):
    n=A.shape[0]
    Q=np.zeros((n,n))
    R=np.zeros((n,n))
    for k in range(n):
        b=np.zeros(n)
        if k==0:
            b=A[:,0:1]
            d=np.linalg.norm(b)
            Q[:,0:1]=b/d
        else:
            b=A[:,k:k+1]
            for j in range(k):
                b-=(A[:,k:k+1].T@Q[:,j:j+1])*Q[:,j:j+1]
            d=np.linalg.norm(b)
            Q[:,k:k+1]=b/d
    R=Q.T@A
    return Q,R 

A=np.arange(9).reshape(3,3).astype(np.float64)
Q,R=Schmidt(A)
print(Q)
print(R)

[[ 0.          0.91287093  0.66666667]
 [ 0.4472136   0.36514837  0.66666667]
 [ 0.89442719 -0.18257419 -0.33333333]]
[[6.70820393 0.         0.        ]
 [0.         1.09544512 0.        ]
 [0.         1.         0.        ]]
